version: '3'

networks:
  air:
    driver: bridge

services:
  air-postgres:
    image: postgres
    environment:
      POSTGRES_USER: airs
      POSTGRES_PASSWORD: AqD4267
    volumes:
       - postgres-data:/var/lib/postgresql/data
    networks:
      - air
  airs-gunicorn:
    image: vovadenisov/airs:1.5
    ports:
      - "8000:8000"
    volumes:
      - ../conf:/test_air/conf
    networks:
      - air
    command: gunicorn airs.wsgi:application -w 2 --bind 0.0.0.0:8000 --reload --log-level DEBUG
volumes:
  postgres-data:
    driver: local
