# Generated by Django 2.0.6 on 2018-06-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аэропорт')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.PositiveSmallIntegerField(choices=[(0, 'mondey'), (1, 'tuesday'), (2, 'wednesday'), (3, 'thursday'), (4, 'friday'), (5, 'saturday'), (6, 'sunday')], verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название самолета')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='air_schedule.Plane', verbose_name='Самолет'),
        ),
        migrations.AddField(
            model_name='flight',
            name='start_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_flight', to='air_schedule.Airport', verbose_name='Стартовый аэропорт'),
        ),
        migrations.AddField(
            model_name='flight',
            name='target_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_flight', to='air_schedule.Airport', verbose_name='Конечный аэропорт'),
        ),
    ]
