# Generated by Django 2.0.6 on 2018-06-14 18:31

from django.db import migrations


def create_schedule(apps, schema_editor):
    Airport = apps.get_model('air_schedule', 'Airport')
    Flight = apps.get_model('air_schedule', 'Flight')
    Plane = apps.get_model('air_schedule', 'Plane')

    Airport.objects.create(name="Симферополь")
    Airport.objects.create(name="Домодедово")
    Airport.objects.create(name="Внуково")
    Airport.objects.create(name="Шереметьево")
    Airport.objects.create(name="Пулково")

    Plane.objects.create(name="Boeing 747-400")
    Plane.objects.create(name="Boeing 747-400")
    Plane.objects.create(name="Boeing 747-400")
    Plane.objects.create(name="Boeing 747-400")
    Plane.objects.create(name="Airbus A380-800")

    start = Airport.objects.filter(name='Шереметьево').first()
    target = Airport.objects.filter(name='Пулково').first()
    for plane in Plane.objects.all()[0: 2]:
        for day in range(0, 7):
            Flight.objects.create(day_of_the_week=day, start_airport=start, target_airport=target, plane=plane)
            Flight.objects.create(day_of_the_week=day, start_airport=target, target_airport=start, plane=plane)

    start = Airport.objects.filter(name='Внуково').first()
    target = Airport.objects.filter(name='Симферополь').first()
    plane = Plane.objects.all()[2]
    for day in range(0, 7):
        Flight.objects.create(day_of_the_week=day, start_airport=start, target_airport=target, plane=plane)
        Flight.objects.create(day_of_the_week=day, start_airport=target, target_airport=start, plane=plane)

    start = Airport.objects.filter(name='Пулково').first()
    target = Airport.objects.filter(name='Домодедово').first()
    plane = Plane.objects.all()[3]
    Flight.objects.create(day_of_the_week=5, start_airport=start, target_airport=target, plane=plane)
    Flight.objects.create(day_of_the_week=6, start_airport=target, target_airport=start, plane=plane)

    start = Airport.objects.filter(name='Домодедово').first()
    target = Airport.objects.filter(name='Симферополь').first()
    plane = Plane.objects.all()[4]
    Flight.objects.create(day_of_the_week=5, start_airport=start, target_airport=target, plane=plane)
    Flight.objects.create(day_of_the_week=6, start_airport=target, target_airport=start, plane=plane)


class Migration(migrations.Migration):

    dependencies = [
        ('air_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_schedule)
    ]
